export { GestaoUsuariosPage } from './GestaoUsuariosPage';
export { AdminFormPage } from './AdminFormPage';
export { AgenteFormPage } from './AgenteFormPage';
export { PcdPublicFormPage } from './PcdPublicFormPage'; 
export { PcdAdminFormPage } from './PcdAdminFormPage';   
export { PcdDashboardPage } from './PcdDashboardPage';
export { PcdProfilePage } from './PcdProfilePage';
export { AgenteDashboardPage } from './AgenteDashboardPage';
export { AdminHomePage } from './AdminHomePage';